name: vlmaps-6
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # === Core Infrastructure ===
  # HARD CONSTRAINT: Pinning to your required Python version.
  - python=3.8.20
  - pip
  - pytorch-cuda=11.8

  # === Deep Learning & ML ===
  # PINNED: Using versions from your original environment for compatibility.
  - pytorch=2.1
  - torchvision
  - torchaudio
  - scikit-learn=1.3.2
  - transformers=4.46.3
  - timm=1.0.15

  # === Computer Vision ===
  - opencv
  - pillow=9.4.0
  
  # === Data Handling & Utilities ===
  # PINNED: Using versions from your original environment.
  - numpy=1.24.4
  - scipy=1.10.1
  - pandas=2.0.3
  - h5py=3.11.0
  - matplotlib=3.7.5
  - tqdm
  - pyyaml

  # === Notebook & Environment ===
  - jupyterlab
  - ipywidgets
  - mat73
  
  # === Pip Packages ===
  - pip:
    - pycolmap
    - hloc
    - yacs
    - detectron2
    - ftfy
    - gdown
    - kaggle
    - einops